power <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, na.strings = "?",)
power$Date <- as.Date.factor(power$Date, "%d/%m/%Y")
power <- subset(power, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
power$Time <- paste(power$Date, power$Time, sep = " ")
power$Time <- strptime(power$Time, "%Y-%m-%d %H:%M:%S")
png(filename = "plot3.png", width = 480, height = 480, bg = "transparent")
plot(power$Time,power$Sub_metering_1, type = "n", ylab = "Energy sub metering", xlab = "")
lines(power$Time,power$Sub_metering_1)
lines(power$Time,power$Sub_metering_2, col = "red")
lines(power$Time,power$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, col = c("black", "red", "blue"))
dev.off()